name: My Action Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run my Docker Action
      uses: ./
      with:
        my_input: Printing Hello World from Powershell
